import React, { useState } from "react";
import {
  Globe,
  Key,
  Server,
  ShieldCheck,
  CheckCircle2,
  XCircle,
  AlertCircle,
  Save,
  RotateCcw,
  RefreshCw,
  Eye,
  Edit3,
  Check,
  X,
  Zap,
  Sliders,
  Send,
  Lock,
  FileText,
  Clock,
  Sparkles,
  Download,
  Copy,
  Cpu,
  Layers,
  Activity,
  Trash2,
  Filter,
  Search,
  CheckSquare,
  Shield,
  Radio,
  ExternalLink
} from "lucide-react";

export interface ApiKeyRecord {
  keyId: string;
  serviceName: string;
  status: "Active" | "Inactive" | "Sandbox";
  environment: "Live Prod" | "Test Mode";
  rateLimit: string;
  lastSync: string;
}

export interface ConnectorService {
  name: string;
  category: string;
  status: "Active" | "Inactive" | "Degraded";
  latency: string;
  apiKeySnippet: string;
}

export const API_WORKFLOW = [
  "Service Integration Selected",
  "API Keys Generated",
  "Webhook Endpoint Registered",
  "IP Restrictions Configured",
  "Connection Test Verified",
  "Integration Saved to Database"
];

export const API_FEATURES = [
  "Third-party Service Connectors",
  "Encrypted API Key Storage",
  "Custom Webhook Listeners",
  "Rate Limiting Enforcement",
  "IP Whitelisting Security",
  "Granular API Scopes",
  "Real-time Latency Metrics",
  "Automated Failover Routing",
  "Comprehensive API Audit Trail",
  "Test Sandbox Environment"
];

export const LAYOUT_CATALOG = [
  "API Integration",
  "Statistics Cards",
  "Active Integrations",
  "Key Config Form",
  "API Keys Table",
  "Activity Stream Logs",
  "Security Standards",
  "Quick Actions"
];

const MOCK_CONNECTORS: ConnectorService[] = [
  { name: "Embassy Visa Portal API", category: "Embassy Portal", status: "Active", latency: "110 ms", apiKeySnippet: "emb_live_9988" },
  { name: "Passport Verification API", category: "Verification", status: "Active", latency: "95 ms", apiKeySnippet: "pass_ver_4432" },
  { name: "Razorpay Payment API", category: "Payment Gateway", status: "Active", latency: "140 ms", apiKeySnippet: "rzp_live_1234" },
  { name: "Twilio SMS Gateway API", category: "SMS Gateway", status: "Active", latency: "120 ms", apiKeySnippet: "twi_live_5566" },
  { name: "SendGrid Email API", category: "Email Gateway", status: "Active", latency: "130 ms", apiKeySnippet: "sg_live_7788" },
  { name: "AWS S3 Storage API", category: "Cloud Storage", status: "Active", latency: "85 ms", apiKeySnippet: "aws_s3_9900" },
  { name: "Immigration Portal API", category: "Govt Immigration", status: "Active", latency: "105 ms", apiKeySnippet: "gov_imm_1122" },
  { name: "WhatsApp Business API", category: "Messaging", status: "Active", latency: "115 ms", apiKeySnippet: "wa_biz_3344" },
  { name: "Document OCR AI Service", category: "AI & Extraction", status: "Active", latency: "210 ms", apiKeySnippet: "ocr_ai_5566" },
  { name: "Currency Exchange Rate API", category: "Finance Data", status: "Active", latency: "75 ms", apiKeySnippet: "forex_live_7788" },
  { name: "Identity KYC Verification API", category: "Identity", status: "Active", latency: "135 ms", apiKeySnippet: "kyc_ver_9900" },
  { name: "Address Validation API", category: "Geo Data", status: "Active", latency: "90 ms", apiKeySnippet: "geo_addr_1234" }
];

const MOCK_API_KEYS: ApiKeyRecord[] = [
  { keyId: "KEY-9001", serviceName: "Embassy Portal API", status: "Active", environment: "Live Prod", rateLimit: "500 req/min", lastSync: "2 Mins Ago" },
  { keyId: "KEY-9002", serviceName: "Passport Verification API", status: "Active", environment: "Live Prod", rateLimit: "200 req/min", lastSync: "5 Mins Ago" },
  { keyId: "KEY-9003", serviceName: "Razorpay Gateway", status: "Active", environment: "Live Prod", rateLimit: "1000 req/min", lastSync: "1 Min Ago" },
  { keyId: "KEY-9004", serviceName: "Twilio SMS Service", status: "Sandbox", environment: "Test Mode", rateLimit: "100 req/min", lastSync: "15 Mins Ago" }
];

const MOCK_ACTIVITY_LOGS = [
  { time: "2 Mins Ago", event: "POST /api/v1/webhooks/embassy -> 200 OK (112ms)", status: "Success" },
  { time: "8 Mins Ago", event: "SendGrid API Key regenerated by Super Admin", status: "Security" },
  { time: "15 Mins Ago", event: "Partner API hit 80% quota threshold (800 req/min)", status: "Warning" },
  { time: "22 Mins Ago", event: "AWS S3 Health Ping -> 200 OK (85ms)", status: "Success" },
  { time: "30 Mins Ago", event: "Passport Verification API Response Success (95ms)", status: "Success" }
];

export default function ApiIntegrationManagement() {
  // Config States
  const [integrationName, setIntegrationName] = useState("Partner Portal API");
  const [accessTier, setAccessTier] = useState("Public");
  const [apiKey, setApiKey] = useState("phtm_live_key_9876543210");
  const [webhookUrl, setWebhookUrl] = useState("https://phantomvisa.com/api/v1/webhooks/listener");
  const [secretKey, setSecretKey] = useState("whsec_secret_9988776655");
  const [allowedIpRange, setAllowedIpRange] = useState("192.168.1.0/24");
  const [rateLimitCap, setRateLimitCap] = useState("1,000 Requests / Min");

  // Search & Filter
  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("All");

  // UI Toast Notification
  const [toastMsg, setToastMsg] = useState<string | null>(null);
  const triggerToast = (msg: string) => {
    setToastMsg(msg);
    setTimeout(() => setToastMsg(null), 3000);
  };

  const handleGenerateKey = () => {
    const newKey = `phtm_live_${Math.random().toString(36).substring(2, 12)}`;
    setApiKey(newKey);
    triggerToast("Generated new API Key successfully.");
  };

  const handleTestConnection = () => {
    triggerToast("Pinging external API services... All 12 integrations 200 OK (124ms avg).");
  };

  const handleSaveApiSettings = () => {
    triggerToast("API Integration configuration and Webhooks saved.");
  };

  const handleRotateSecrets = () => {
    triggerToast("Rotated secret keys for all active integrations.");
  };

  const handleExportAudit = () => {
    triggerToast("Exporting API Integration audit report (CSV)...");
  };

  const handleFlushCache = () => {
    triggerToast("Flushed API cache & reset connection pools.");
  };

  return (
    <div className="w-full bg-[#F8FAFC] text-slate-800 font-sans min-h-screen p-4 sm:p-6 lg:p-8 animate-in fade-in duration-200">
      {/* TOAST NOTIFICATION */}
      {toastMsg && (
        <div className="fixed top-5 right-5 z-50 bg-[#0E1A2C] border border-[#2563EB]/40 text-white px-4 py-3 rounded-xl shadow-2xl flex items-center gap-3 animate-in slide-in-from-top-3">
          <div className="w-8 h-8 rounded-lg bg-[#2563EB]/20 flex items-center justify-center text-[#2563EB]">
            <CheckCircle2 size={18} />
          </div>
          <span className="text-xs font-semibold">{toastMsg}</span>
        </div>
      )}

      {/* HEADER SECTION */}
      <div className="bg-gradient-to-r from-[#1E3A8A] via-[#2563EB] to-[#3B82F6] text-white p-6 rounded-3xl shadow-xl mb-6 flex flex-col sm:flex-row sm:items-center justify-between gap-4 border border-blue-700">
        <div>
          <div className="flex items-center gap-2 text-xs font-mono text-blue-200 mb-1">
            <Globe size={15} />
            <span className="px-2.5 py-0.5 rounded-full bg-white/10 border border-white/20 font-bold">
              Settings &bull; External API & Webhook Integrations
            </span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-black text-white tracking-tight font-outfit">
            API Integration
          </h1>
          <p className="text-xs text-blue-100 font-medium mt-1">
            Manage third-party API integrations, webhook endpoints, API keys, rate limits, and external service connectors.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleTestConnection}
            className="px-4 py-2.5 bg-white/10 hover:bg-white/20 text-white font-bold rounded-2xl text-xs backdrop-blur-md transition cursor-pointer flex items-center gap-1.5 border border-white/20"
          >
            <Zap size={15} /> Test All Connections
          </button>
          <button
            onClick={handleSaveApiSettings}
            className="px-4 py-2.5 bg-white text-[#2563EB] hover:bg-blue-50 font-extrabold rounded-2xl text-xs shadow-md transition cursor-pointer flex items-center gap-2"
          >
            <Save size={15} /> Save API Settings
          </button>
        </div>
      </div>

      {/* TOP METRICS DASHBOARD (6 CARDS MATCHING WIREFRAME) */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3.5 mb-6">
        <div className="bg-white border border-slate-200 rounded-3xl p-4 shadow-2xs hover:shadow-md transition">
          <span className="text-[10px] font-extrabold uppercase text-slate-500 block mb-1">Active Integrations</span>
          <div className="text-2xl font-black text-slate-900 font-mono">12</div>
          <span className="text-[10px] text-[#2563EB] font-bold">Connected Services</span>
        </div>

        <div className="bg-white border border-slate-200 rounded-3xl p-4 shadow-2xs hover:shadow-md transition">
          <span className="text-[10px] font-extrabold uppercase text-blue-600 block mb-1">API Requests (24h)</span>
          <div className="text-2xl font-black text-slate-900 font-mono">148,920</div>
          <span className="text-[10px] text-blue-600 font-bold">High Volume Traffic</span>
        </div>

        <div className="bg-white border border-slate-200 rounded-3xl p-4 shadow-2xs hover:shadow-md transition">
          <span className="text-[10px] font-extrabold uppercase text-emerald-600 block mb-1">Average Latency</span>
          <div className="text-2xl font-black text-slate-900 font-mono">124 ms</div>
          <span className="text-[10px] text-emerald-600 font-bold">Fast Response</span>
        </div>

        <div className="bg-white border border-slate-200 rounded-3xl p-4 shadow-2xs hover:shadow-md transition">
          <span className="text-[10px] font-extrabold uppercase text-purple-600 block mb-1">Webhook Endpoints</span>
          <div className="text-2xl font-black text-slate-900 font-mono">6</div>
          <span className="text-[10px] text-purple-600 font-bold">Listening Streams</span>
        </div>

        <div className="bg-white border border-slate-200 rounded-3xl p-4 shadow-2xs hover:shadow-md transition">
          <span className="text-[10px] font-extrabold uppercase text-teal-600 block mb-1">Success Rate</span>
          <div className="text-2xl font-black text-slate-900 font-mono">99.8%</div>
          <span className="text-[10px] text-teal-600 font-bold">High Reliability</span>
        </div>

        <div className="bg-white border border-slate-200 rounded-3xl p-4 shadow-2xs hover:shadow-md transition">
          <span className="text-[10px] font-extrabold uppercase text-emerald-600 block mb-1">System Status</span>
          <div className="text-xl font-black text-slate-900 font-mono">Connected 🟢</div>
          <span className="text-[10px] text-emerald-600 font-bold">All APIs Online</span>
        </div>
      </div>

      {/* ACTIVE THIRD-PARTY INTEGRATIONS GRID CATALOG */}
      <div className="bg-white border border-slate-200 rounded-3xl p-5 shadow-2xs mb-6 space-y-4">
        <h3 className="text-xs font-extrabold text-slate-900 uppercase tracking-wider font-outfit border-b border-slate-100 pb-3 flex items-center justify-between">
          <span className="flex items-center gap-2">
            <Cpu size={16} className="text-[#2563EB]" /> Connected Third-Party Service Connectors (12 Active)
          </span>
          <span className="text-[11px] font-mono text-emerald-700 bg-emerald-50 px-2.5 py-0.5 rounded-full font-bold">
            100% Operational Health
          </span>
        </h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
          {MOCK_CONNECTORS.map((c, idx) => (
            <div key={idx} className="bg-slate-50 border border-slate-200 p-3.5 rounded-2xl hover:border-blue-300 transition space-y-2">
              <div className="flex justify-between items-start">
                <span className="text-[10px] font-extrabold uppercase text-blue-700 bg-blue-50 px-2 py-0.5 rounded">
                  {c.category}
                </span>
                <span className="text-[10px] font-bold text-emerald-700 flex items-center gap-1">
                  🟢 {c.status}
                </span>
              </div>
              <h4 className="text-xs font-bold text-slate-900 font-outfit">{c.name}</h4>
              <div className="flex justify-between items-center text-[10px] text-slate-500 font-mono">
                <span>Latency: <strong className="text-slate-800">{c.latency}</strong></span>
                <span>Key: <strong className="text-slate-800">{c.apiKeySnippet}</strong></span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* MAIN CONTENT GRID */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
        {/* LEFT 2 COLUMNS: FORM, TABLE, STREAM LOGS & STANDARDS */}
        <div className="lg:col-span-2 space-y-6">
          {/* API KEY & WEBHOOK GENERATOR FORM */}
          <div className="bg-white border border-slate-200 rounded-3xl p-5 shadow-2xs space-y-4">
            <h3 className="text-xs font-extrabold text-slate-900 uppercase tracking-wider font-outfit border-b border-slate-100 pb-3 flex items-center gap-2">
              <Key size={16} className="text-[#2563EB]" /> API Key Generation & Webhook Config
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
              <div>
                <label className="text-[10px] font-extrabold uppercase text-slate-500 block mb-1">Integration Name</label>
                <input
                  type="text"
                  value={integrationName}
                  onChange={(e) => setIntegrationName(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-200 text-slate-800 text-xs px-3 py-2 rounded-xl font-semibold"
                />
              </div>

              <div>
                <label className="text-[10px] font-extrabold uppercase text-slate-500 block mb-1">API Access Tier</label>
                <select
                  value={accessTier}
                  onChange={(e) => setAccessTier(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-200 text-slate-800 text-xs px-3 py-2 rounded-xl font-bold"
                >
                  <option value="Public">Public API (Partner Access)</option>
                  <option value="Internal">Internal Platform Scope</option>
                  <option value="Private">Private Confidential</option>
                </select>
              </div>

              <div>
                <label className="text-[10px] font-extrabold uppercase text-slate-500 block mb-1">Generated API Key</label>
                <div className="relative">
                  <input
                    type="text"
                    value={apiKey}
                    readOnly
                    className="w-full bg-slate-100 border border-slate-200 text-slate-900 text-xs px-3 py-2 rounded-xl font-mono font-bold pr-10"
                  />
                  <button
                    type="button"
                    onClick={handleGenerateKey}
                    className="absolute right-2 top-2 p-1 text-[#2563EB] hover:bg-blue-50 rounded-lg transition"
                  >
                    <RefreshCw size={14} />
                  </button>
                </div>
              </div>

              <div>
                <label className="text-[10px] font-extrabold uppercase text-slate-500 block mb-1">Webhook Receiver URL</label>
                <input
                  type="text"
                  value={webhookUrl}
                  onChange={(e) => setWebhookUrl(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-200 text-slate-800 text-xs px-3 py-2 rounded-xl font-mono text-slate-600"
                />
              </div>

              <div>
                <label className="text-[10px] font-extrabold uppercase text-slate-500 block mb-1">Secret Signing Key</label>
                <input
                  type="password"
                  value={secretKey}
                  onChange={(e) => setSecretKey(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-200 text-slate-800 text-xs px-3 py-2 rounded-xl font-mono"
                />
              </div>

              <div>
                <label className="text-[10px] font-extrabold uppercase text-slate-500 block mb-1">Allowed IP Range</label>
                <input
                  type="text"
                  value={allowedIpRange}
                  onChange={(e) => setAllowedIpRange(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-200 text-slate-800 text-xs px-3 py-2 rounded-xl font-mono"
                />
              </div>
            </div>
          </div>

          {/* CONFIGURED API KEYS TABLE */}
          <div className="bg-white border border-slate-200 rounded-3xl p-5 shadow-2xs space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-slate-100 pb-3 gap-2">
              <h3 className="text-xs font-extrabold text-slate-900 uppercase tracking-wider font-outfit flex items-center gap-2">
                <Server size={16} className="text-[#2563EB]" /> Configured API Key Credentials & Status
              </h3>
              <div className="flex items-center gap-2">
                <div className="relative w-44">
                  <Search size={13} className="absolute left-2.5 top-2 text-slate-400" />
                  <input
                    type="text"
                    placeholder="Search keys..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="w-full bg-slate-50 border border-slate-200 text-slate-800 text-[11px] pl-8 pr-2 py-1 rounded-xl focus:outline-none"
                  />
                </div>
              </div>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead>
                  <tr className="text-[10px] text-slate-400 font-bold uppercase border-b border-slate-100">
                    <th className="pb-2">Key ID</th>
                    <th className="pb-2">Service Name</th>
                    <th className="pb-2 text-center">Status</th>
                    <th className="pb-2 text-center">Environment</th>
                    <th className="pb-2 text-center">Rate Limit</th>
                    <th className="pb-2 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 font-medium">
                  {MOCK_API_KEYS.map((k) => (
                    <tr key={k.keyId} className="hover:bg-slate-50">
                      <td className="py-2.5 font-mono font-bold text-slate-900">{k.keyId}</td>
                      <td className="py-2.5 font-bold text-slate-900 flex items-center gap-1.5">
                        <Globe size={14} className="text-[#2563EB]" />
                        <span>{k.serviceName}</span>
                      </td>
                      <td className="py-2.5 text-center">
                        <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                          k.status === "Active" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"
                        }`}>
                          {k.status === "Active" ? "🟢 Active" : "🟡 Sandbox"}
                        </span>
                      </td>
                      <td className="py-2.5 text-center font-mono text-[11px] text-slate-600">{k.environment}</td>
                      <td className="py-2.5 text-center font-mono font-bold text-blue-700">{k.rateLimit}</td>
                      <td className="py-2.5 text-right space-x-1">
                        <button
                          onClick={() => triggerToast(`Regenerating key for ${k.serviceName}`)}
                          className="p-1.5 bg-slate-100 hover:bg-blue-50 text-slate-600 hover:text-[#2563EB] rounded-lg transition"
                        >
                          <RefreshCw size={13} />
                        </button>
                        <button
                          onClick={() => triggerToast(`Deactivating key ${k.keyId}`)}
                          className="p-1.5 bg-red-50 hover:bg-red-100 text-red-600 rounded-lg transition"
                        >
                          <Trash2 size={13} />
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* API REQUEST & WEBHOOK ACTIVITY STREAM LOGS */}
          <div className="bg-white border border-slate-200 rounded-3xl p-5 shadow-2xs space-y-3">
            <h3 className="text-xs font-extrabold text-slate-900 uppercase tracking-wider font-outfit border-b border-slate-100 pb-2 flex items-center gap-2">
              <Activity size={16} className="text-purple-600" /> API Activity & Webhook Event Stream
            </h3>
            <div className="space-y-2 font-mono text-xs">
              {MOCK_ACTIVITY_LOGS.map((act, idx) => (
                <div key={idx} className="bg-slate-50 p-2.5 rounded-xl border border-slate-100 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className={`w-2 h-2 rounded-full ${
                      act.status === "Success" ? "bg-emerald-500" : act.status === "Security" ? "bg-blue-500" : "bg-amber-500"
                    }`} />
                    <span className="text-slate-800 font-semibold">{act.event}</span>
                  </div>
                  <span className="text-[10px] text-slate-400">{act.time}</span>
                </div>
              ))}
            </div>
          </div>

          {/* SECURITY & PROTOCOL STANDARDS CARD */}
          <div className="bg-white border border-slate-200 rounded-3xl p-5 shadow-2xs space-y-3">
            <h3 className="text-xs font-extrabold text-slate-900 uppercase tracking-wider font-outfit border-b border-slate-100 pb-2 flex items-center gap-2">
              <ShieldCheck size={16} className="text-emerald-600" /> API Security & Protocol Standards
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs font-semibold">
              <div className="bg-emerald-50/70 p-2.5 rounded-xl border border-emerald-100 flex justify-between">
                <span>Auth Standard:</span>
                <span className="font-bold text-emerald-800 font-mono">Bearer Token / OAuth2</span>
              </div>
              <div className="bg-emerald-50/70 p-2.5 rounded-xl border border-emerald-100 flex justify-between">
                <span>TLS Mandate:</span>
                <span className="font-bold text-emerald-800 font-mono">TLS 1.3 Active</span>
              </div>
              <div className="bg-emerald-50/70 p-2.5 rounded-xl border border-emerald-100 flex justify-between">
                <span>Payload Encryption:</span>
                <span className="font-bold text-emerald-800 font-mono">AES-256 GCM</span>
              </div>
              <div className="bg-emerald-50/70 p-2.5 rounded-xl border border-emerald-100 flex justify-between">
                <span>Rate Limit Algorithm:</span>
                <span className="font-bold text-emerald-800 font-mono">Token Bucket</span>
              </div>
            </div>
          </div>
        </div>

        {/* RIGHT COLUMN: ACTIONS, CATALOG & WORKFLOW */}
        <div className="space-y-6">
          {/* QUICK CONTROL ACTIONS */}
          <div className="bg-white border border-slate-200 rounded-3xl p-5 shadow-2xs space-y-2">
            <h3 className="text-xs font-extrabold text-slate-900 uppercase tracking-wider font-outfit border-b border-slate-100 pb-2 flex items-center gap-2">
              <Zap size={16} className="text-[#2563EB]" /> API Control Actions
            </h3>
            <div className="space-y-2">
              <button
                onClick={handleGenerateKey}
                className="w-full py-2 bg-[#2563EB] hover:bg-blue-700 text-white font-extrabold rounded-xl text-xs transition cursor-pointer flex items-center justify-center gap-2"
              >
                <Key size={14} /> Generate New API Key
              </button>
              <button
                onClick={handleTestConnection}
                className="w-full py-2 bg-emerald-600 hover:bg-emerald-700 text-white font-extrabold rounded-xl text-xs transition cursor-pointer flex items-center justify-center gap-2"
              >
                <Zap size={14} /> Test Service Connections
              </button>
              <button
                onClick={handleRotateSecrets}
                className="w-full py-2 bg-purple-600 hover:bg-purple-700 text-white font-extrabold rounded-xl text-xs transition cursor-pointer flex items-center justify-center gap-2"
              >
                <RotateCcw size={14} /> Rotate Secret Keys
              </button>
              <button
                onClick={handleExportAudit}
                className="w-full py-2 bg-slate-100 hover:bg-slate-200 text-slate-800 font-bold rounded-xl text-xs transition cursor-pointer flex items-center justify-center gap-2"
              >
                <Download size={14} /> Export API Audit Report
              </button>
              <button
                onClick={handleFlushCache}
                className="w-full py-2 bg-amber-500 hover:bg-amber-600 text-white font-extrabold rounded-xl text-xs transition cursor-pointer flex items-center justify-center gap-2"
              >
                <RefreshCw size={14} /> Flush API Cache
              </button>
            </div>
          </div>

          {/* DASHBOARD LAYOUT CATALOG */}
          <div className="bg-white border border-slate-200 rounded-3xl p-5 shadow-2xs space-y-3">
            <h3 className="text-xs font-extrabold text-slate-900 uppercase tracking-wider font-outfit border-b border-slate-100 pb-2 flex items-center gap-2">
              <Layers size={16} className="text-[#2563EB]" /> Dashboard Layout Catalog
            </h3>
            <div className="flex flex-wrap gap-1.5">
              {LAYOUT_CATALOG.map((item, idx) => (
                <span key={idx} className="bg-slate-100 text-slate-700 text-[10px] font-bold px-2.5 py-1 rounded-lg">
                  {item}
                </span>
              ))}
            </div>
          </div>

          {/* API INTEGRATION WORKFLOW */}
          <div className="bg-white border border-slate-200 rounded-3xl p-5 shadow-2xs space-y-3">
            <h3 className="text-xs font-extrabold text-slate-900 uppercase tracking-wider font-outfit border-b border-slate-100 pb-2 flex items-center gap-2">
              <Clock size={16} className="text-emerald-600" /> Integration Setup Workflow
            </h3>
            <div className="space-y-2">
              {API_WORKFLOW.map((step, idx) => (
                <div key={idx} className="flex items-center gap-2 text-xs">
                  <span className="w-5 h-5 rounded-full bg-blue-100 text-blue-700 font-extrabold flex items-center justify-center text-[10px]">
                    {idx + 1}
                  </span>
                  <span className="font-semibold text-slate-800">{step}</span>
                </div>
              ))}
            </div>
          </div>

          {/* PROFESSIONAL FEATURES CATALOG */}
          <div className="bg-white border border-slate-200 rounded-3xl p-5 shadow-2xs space-y-3">
            <h3 className="text-xs font-extrabold text-slate-900 uppercase tracking-wider font-outfit border-b border-slate-100 pb-2 flex items-center gap-2">
              <Sparkles size={16} className="text-purple-600" /> Professional Features Catalog
            </h3>
            <div className="space-y-1.5 text-xs">
              {API_FEATURES.map((feat, idx) => (
                <div key={idx} className="flex items-center gap-2 text-slate-700 font-medium">
                  <CheckCircle2 size={13} className="text-emerald-600 shrink-0" />
                  <span>{feat}</span>
                </div>
              ))}
            </div>
          </div>

          {/* RECOMMENDATION BOX */}
          <div className="bg-blue-50/50 border border-blue-200 rounded-3xl p-5 space-y-2">
            <h3 className="text-xs font-extrabold text-slate-900 uppercase tracking-wider font-outfit flex items-center gap-2 border-b border-blue-100 pb-2">
              <ShieldCheck size={16} className="text-[#2563EB]" /> Professional Recommendation
            </h3>
            <p className="text-[11px] text-slate-600 leading-relaxed font-medium">
              The API Integration page manages external service connectors (Embassy Portals, Passport Verification, Razorpay, Twilio, SendGrid, AWS S3). Configure API keys, secret tokens, webhook endpoints, rate limits, IP restrictions, and monitor real-time latency and connection health.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
